// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCQKRVoHDkj9o5QuQWXHZySjtzIGuH-89Y",
    authDomain: "ebooks-634b9.firebaseapp.com",
    projectId: "ebooks-634b9",
    storageBucket: "ebooks-634b9.firebasestorage.app",
    messagingSenderId: "467475097931",
    appId: "1:467475097931:web:86fd4499b00a6457d4e0ce",
    measurementId: "G-RV9ZS4JNZS",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQKRVoHDkj9o5QuQWXHZySjtzIGuH-89Y',
    appId: '1:467475097931:web:86fd4499b00a6457d4e0ce',
    messagingSenderId: '467475097931',
    projectId: 'ebooks-634b9',
    storageBucket: 'ebooks-634b9.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDqCVsA1-xlHgNDhtSHpvI4qRM98zVBgOA',
  //   appId: '1:545059185697:ios:45f15c5756e4e9eda9af60',
  //   messagingSenderId: '545059185697',
  //   projectId: 'healthful-dev',
  //   storageBucket: 'healthful-dev.firebasestorage.app',
  //   iosBundleId: 'com.hifah.healthful',
  // );
}

// appId-> ca-app-pub-5403313078782320~4199146521

//banner ad-> ca-app-pub-5403313078782320/3352968710

//Interstitial ad-> ca-app-pub-5403313078782320/2039887047
